name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 22
        uses: actions/setup-java@v4.2.2
        with:
          distribution: temurin
          java-version-file: .java-version

      - name: Build with Maven
        run: chmod +x ./mvnw && ./mvnw clean package -P ci -DfinalName=app

      - name: Log in to Docker Hub
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      - name: Build Docker image
        run: docker build -t djajcevic/spring-demo:${{ github.sha }} .

      - name: Push Docker image to internal registry
        run: docker push djajcevic/spring-demo:${{ github.sha }}
