name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 22
        uses: actions/setup-java@v4.2.2
        with:
          distribution: temurin
          java-version-file: .java-version

      - name: Build and Test with Maven
        run: chmod +x ./mvnw && ./mvnw clean package -P ci -DfinalName=app

      - name: Docker Login
        # You may pin to the exact commit or the version.
        # uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        uses: docker/login-action@v3.3.0
        with:
          # Username used to log against the Docker registry
          username: "${{ secrets.DOCKER_USER }}"
          # Password or personal access token used to log against the Docker registry
          password: "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build Docker image
        run: docker build -t djajcevic/spring-demo:${{ github.sha }} .

      - name: Push Docker image to internal registry
        run: docker push djajcevic/spring-demo:${{ github.sha }}